
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'ButtonsClearCharts': typeof import("../components/Buttons/ClearCharts.vue")['default']
    'ButtonsExploreBtn': typeof import("../components/Buttons/ExploreBtn.vue")['default']
    'ButtonsExportBtn': typeof import("../components/Buttons/ExportBtn.vue")['default']
    'ButtonsExportExploreBtn': typeof import("../components/Buttons/ExportExploreBtn.vue")['default']
    'ChartsDrawChart': typeof import("../components/Charts/DrawChart.vue")['default']
    'ChartsEloOverTimeChart': typeof import("../components/Charts/EloOverTimeChart.vue")['default']
    'ChartsLossChart': typeof import("../components/Charts/LossChart.vue")['default']
    'ChartsOpeningChart': typeof import("../components/Charts/OpeningChart.vue")['default']
    'ChartsResByRating': typeof import("../components/Charts/ResByRating.vue")['default']
    'ChartsWinChart': typeof import("../components/Charts/WinChart.vue")['default']
    'ExploreTable': typeof import("../components/ExploreTable.vue")['default']
    'ExportPopup': typeof import("../components/ExportPopup.vue")['default']
    'InputForm': typeof import("../components/InputForm.vue")['default']
    'NavBar': typeof import("../components/NavBar.vue")['default']
    'ProgBar': typeof import("../components/ProgBar.vue")['default']
    'UserOverview': typeof import("../components/UserOverview.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyButtonsClearCharts': typeof import("../components/Buttons/ClearCharts.vue")['default']
    'LazyButtonsExploreBtn': typeof import("../components/Buttons/ExploreBtn.vue")['default']
    'LazyButtonsExportBtn': typeof import("../components/Buttons/ExportBtn.vue")['default']
    'LazyButtonsExportExploreBtn': typeof import("../components/Buttons/ExportExploreBtn.vue")['default']
    'LazyChartsDrawChart': typeof import("../components/Charts/DrawChart.vue")['default']
    'LazyChartsEloOverTimeChart': typeof import("../components/Charts/EloOverTimeChart.vue")['default']
    'LazyChartsLossChart': typeof import("../components/Charts/LossChart.vue")['default']
    'LazyChartsOpeningChart': typeof import("../components/Charts/OpeningChart.vue")['default']
    'LazyChartsResByRating': typeof import("../components/Charts/ResByRating.vue")['default']
    'LazyChartsWinChart': typeof import("../components/Charts/WinChart.vue")['default']
    'LazyExploreTable': typeof import("../components/ExploreTable.vue")['default']
    'LazyExportPopup': typeof import("../components/ExportPopup.vue")['default']
    'LazyInputForm': typeof import("../components/InputForm.vue")['default']
    'LazyNavBar': typeof import("../components/NavBar.vue")['default']
    'LazyProgBar': typeof import("../components/ProgBar.vue")['default']
    'LazyUserOverview': typeof import("../components/UserOverview.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ButtonsClearCharts: typeof import("../components/Buttons/ClearCharts.vue")['default']
export const ButtonsExploreBtn: typeof import("../components/Buttons/ExploreBtn.vue")['default']
export const ButtonsExportBtn: typeof import("../components/Buttons/ExportBtn.vue")['default']
export const ButtonsExportExploreBtn: typeof import("../components/Buttons/ExportExploreBtn.vue")['default']
export const ChartsDrawChart: typeof import("../components/Charts/DrawChart.vue")['default']
export const ChartsEloOverTimeChart: typeof import("../components/Charts/EloOverTimeChart.vue")['default']
export const ChartsLossChart: typeof import("../components/Charts/LossChart.vue")['default']
export const ChartsOpeningChart: typeof import("../components/Charts/OpeningChart.vue")['default']
export const ChartsResByRating: typeof import("../components/Charts/ResByRating.vue")['default']
export const ChartsWinChart: typeof import("../components/Charts/WinChart.vue")['default']
export const ExploreTable: typeof import("../components/ExploreTable.vue")['default']
export const ExportPopup: typeof import("../components/ExportPopup.vue")['default']
export const InputForm: typeof import("../components/InputForm.vue")['default']
export const NavBar: typeof import("../components/NavBar.vue")['default']
export const ProgBar: typeof import("../components/ProgBar.vue")['default']
export const UserOverview: typeof import("../components/UserOverview.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyButtonsClearCharts: typeof import("../components/Buttons/ClearCharts.vue")['default']
export const LazyButtonsExploreBtn: typeof import("../components/Buttons/ExploreBtn.vue")['default']
export const LazyButtonsExportBtn: typeof import("../components/Buttons/ExportBtn.vue")['default']
export const LazyButtonsExportExploreBtn: typeof import("../components/Buttons/ExportExploreBtn.vue")['default']
export const LazyChartsDrawChart: typeof import("../components/Charts/DrawChart.vue")['default']
export const LazyChartsEloOverTimeChart: typeof import("../components/Charts/EloOverTimeChart.vue")['default']
export const LazyChartsLossChart: typeof import("../components/Charts/LossChart.vue")['default']
export const LazyChartsOpeningChart: typeof import("../components/Charts/OpeningChart.vue")['default']
export const LazyChartsResByRating: typeof import("../components/Charts/ResByRating.vue")['default']
export const LazyChartsWinChart: typeof import("../components/Charts/WinChart.vue")['default']
export const LazyExploreTable: typeof import("../components/ExploreTable.vue")['default']
export const LazyExportPopup: typeof import("../components/ExportPopup.vue")['default']
export const LazyInputForm: typeof import("../components/InputForm.vue")['default']
export const LazyNavBar: typeof import("../components/NavBar.vue")['default']
export const LazyProgBar: typeof import("../components/ProgBar.vue")['default']
export const LazyUserOverview: typeof import("../components/UserOverview.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
